Import('env')
env = env.Clone()

format_cpps = env.aDirs('format')
appender_cpps = env.aDirs('appender')

cpps = [ format_cpps,
         appender_cpps,
]

target = env.aLibraryAndInstall(
            target = 'log4cpp',
            source = cpps,
            LIBS = [],
            package = env['project_name']
)